---

- hosts: all
  roles:
    - role: subscription-manager
      when: ansible_distribution == 'RedHat'
    - role: pulp-priority
    - role: pulp-fips
      when:
        - enable_fips is defined
        - enable_fips
    - role: pulp
    - role: lazy
      when: pulp_version is version('2.8', '>=')
    - role: pulp-certs
    - role: pulp-crane
